/*
 * Copyright (C) 2024 util2
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.wingate.libresa;

import java.awt.BorderLayout;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import org.wingate.libresa.net.Handler;
import org.wingate.libresa.net.Node;
import org.wingate.libresa.net.Server;
import org.wingate.libresa.ui.AlexiaUI;

/**
 *
 * @author util2
 */
public class MainFrame extends javax.swing.JFrame {
    
    private final JScrollPane scrollPaneXML;
    private final JTextPane textPane;
    private final AlexiaUI aui;
    
    private final Server server;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        File currentFolder = new File(".");
        File file = new File(currentFolder.getAbsolutePath() + File.separator + "nodes");
        server = Server.create(localNode(file.getAbsolutePath()));
        
        textPane = new JTextPane();
        scrollPaneXML = new JScrollPane(textPane);
        
        paneXML.setLayout(new BorderLayout());
        paneXML.add(scrollPaneXML, BorderLayout.CENTER);
        aui = new AlexiaUI(this, textPane);
    }

    public Thread getServerThread() {
        return server.getThread();
    }
    
    private Node localNode(String nodesPath){
        Node n = null;
        File folder = new File(nodesPath);
        for(File f : folder.listFiles()){
            if(f.getName().equalsIgnoreCase("mynode.txt")){
                n = Node.create(f.getAbsolutePath());
                break;
            }
        }
        return n;
    }
        
    public static List<Node> fillNodes(String nodesPath){
        List<Node> nodes = new ArrayList<>();
        File folder = new File(nodesPath);
        for(File f : folder.listFiles()){
            if(f.getName().equalsIgnoreCase("mynode.txt")) continue;
            nodes.add(Node.create(f.getAbsolutePath()));
        }
        return nodes;
    }

    public Handler getHandler() {
        return server.getHandler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnGo = new javax.swing.JButton();
        paneXML = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnGo.setText("Go");
        btnGo.setFocusable(false);
        btnGo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGo);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout paneXMLLayout = new javax.swing.GroupLayout(paneXML);
        paneXML.setLayout(paneXMLLayout);
        paneXMLLayout.setHorizontalGroup(
            paneXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        paneXMLLayout.setVerticalGroup(
            paneXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        getContentPane().add(paneXML, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        File currentFolder = new File(".");
        File file = new File(currentFolder, "alexia" + File.separator + "001.xml");
        aui.render(file.getAbsolutePath());
    }//GEN-LAST:event_btnGoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel paneXML;
    // End of variables declaration//GEN-END:variables
}
